site_name: IAW - David Escoriza Martínez

nav:
    - Principal: index.md
    - Acerca de: about.md
    - Prácticas: practicas.md

theme: 
  name: material
  language: es
  palette:
    primary: purple
    accent: lime
  font:
    text: Roboto
  features:
    - navigation.tabs
    - header.autohide
  logo: images/Lorem.png
  




